apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busyboxmulti
  name: busyboxmulti
spec:
  containers:
  - image: busybox
    name: busyboxmulti
    args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    resources: {}
  - image: busybox
    name: busyboxmulti1
    args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
