apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxnewsecret
  name: nginxnewsecret
spec:
  containers:
  - image: nginx
    name: nginxnewsecret
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret2
          key: username
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
