apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxsecret
  name: nginxsecret
spec:
  volumes:
  - name: secvol
    secret: 
      secretName: mysecret2
  containers:
  - image: nginx
    name: nginxsecret
    volumeMounts:
     - name: secvol
       mountPath: /etc/foo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
