apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxtask10
  name: nginxtask10
spec:
  containers:
  - env:
    - name: var1
      value: var1
    image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
