apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busyboxenv
  name: busyboxenv
spec:
  containers:
  - command:
    - env
    image: busybox
    name: busyboxenv
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
