apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxvol
  name: nginxvol
spec:
  volumes:
  - name: cmvolume
    configMap:
      name: cmvolume
  containers:
  - image: nginx
    name: nginxvol
    volumeMounts:
    - name: cmvolume
      mountPath: /etc/lala
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
